export const CATEGORIES = [
  "Food",
  "Petrol",
  "Shopping",
  "Entertainment",
  "Travel",
  "Health",
  "Home",
  "Study Room",
  "Gym",
  "RD",
  "Electricity Bill",
  "Room Rent",
  "Other",
];

export const CATEGORY_COLORS: Record<string, string> = {
  Food: "#2fd3b0",
  Petrol: "#45b6ff",
  Shopping: "#c65cff",
  Entertainment: "#5cff8f",
  Travel: "#5c8fff",
  Health: "#ff4d4f",
  Home: "#ff7a45",
  "Study Room": "#7c6cf6",
  Gym: "#ff5c9d",
  RD: "#0984e3",
  "Electricity Bill": "#f6c945",
  "Room Rent": "#ff8c42",
  Other: "#8b8ea3",
};
