export const SYLLABUS_DETAILED: Record<string, Record<string, string[]>> = {
  "Quantitative Aptitude": {
    "Number System": [
      "Types of Numbers",
      "Factors & Multiples",
      "Prime Numbers",
      "Divisibility Rules",
      "LCM & HCF",
      "Simplification",
      "BODMAS",
      "Surds & Indices",
      "Square & Cube Roots",
      "Unit Digit",
      "Remainder Theorem",
      "Decimal & Fractions",
      "Recurring Decimals",
    ],
    Percentage: [
      "Basics",
      "Increase",
      "Decrease",
      "Successive Percentage",
      "Percentage Conversion",
      "Examination Percentage",
    ],
    "Ratio & Proportion": [
      "Ratio",
      "Proportion",
      "Continued Proportion",
      "Variation",
      "Partnership",
      "Mixture & Alligation",
    ],
    Average: ["Simple Average", "Weighted Average", "Average Speed"],
    "Profit & Loss": [
      "Cost Price",
      "Selling Price",
      "Profit",
      "Loss",
      "Discount",
      "Marked Price",
      "Successive Discount",
      "False Weight",
    ],
    "Simple & Compound Interest": [
      "Simple Interest",
      "Compound Interest",
      "Difference SI & CI",
      "Installments",
      "Depreciation",
      "Population Growth",
    ],
    "Time & Work": [
      "Efficiency",
      "Work & Wages",
      "Pipes & Cisterns",
      "Men-Women-Child Work",
      "Alternate Days",
    ],
    "Time Speed Distance": [
      "Basic Formula",
      "Relative Speed",
      "Average Speed",
      "Boats & Streams",
      "Trains",
      "Race",
      "Circular Track",
    ],
    Algebra: [
      "Basic Algebra",
      "Linear Equation",
      "Quadratic Equation",
      "Polynomial",
      "Identities",
      "Factorization",
      "Surds",
      "Logarithm",
    ],
    Geometry: [
      "Lines",
      "Angles",
      "Triangles",
      "Similarity",
      "Congruency",
      "Quadrilaterals",
      "Polygon",
      "Circle",
      "Tangent",
      "Secant",
      "Chord",
    ],
    Mensuration: [
      "Square",
      "Rectangle",
      "Triangle",
      "Circle",
      "Parallelogram",
      "Rhombus",
      "Trapezium",
      "Cube",
      "Cuboid",
      "Cylinder",
      "Cone",
      "Sphere",
      "Hemisphere",
      "Frustum",
    ],
    Trigonometry: [
      "Trigonometric Ratios",
      "Values",
      "Identities",
      "Complementary Angles",
      "Heights & Distances",
    ],
    "Coordinate Geometry": [
      "Distance Formula",
      "Section Formula",
      "Midpoint",
      "Slope",
      "Equation of Line",
    ],
    "Data Interpretation": [
      "Table",
      "Bar Graph",
      "Pie Chart",
      "Line Graph",
      "Mixed Graph",
      "Caselet DI",
    ],
  },
  Reasoning: {
    Analogy: ["Number", "Letter", "Word", "Figure"],
    Classification: ["Number", "Letter", "Word", "Figure"],
    Series: ["Number", "Alphabet", "Mixed", "Missing Series"],
    "Coding Decoding": [
      "Letter",
      "Number",
      "Substitution",
      "Chinese Coding",
      "Matrix Coding",
    ],
    "Blood Relation": ["Direct", "Coded", "Puzzle"],
    "Direction Sense": ["Distance", "Shortest Path", "Shadow"],
    Ranking: ["Position", "Order", "Comparison"],
    Syllogism: ["Basic", "Venn Diagram", "Only", "Either-Or"],
    "Statement & Conclusion": [
      "Assumption",
      "Inference",
      "Argument",
      "Course of Action",
    ],
    Puzzle: ["Linear", "Circular", "Floor", "Box", "Scheduling"],
    "Seating Arrangement": ["Linear", "Circular", "Square", "Rectangular"],
    "Alphabet Test": ["Word Formation", "Dictionary Order", "Letter Position"],
    "Mathematical Operations": ["Operator Change", "Equation Balance"],
    "Clock & Calendar": ["Clock Angle", "Calendar"],
    "Non Verbal": [
      "Mirror",
      "Water Image",
      "Paper Folding",
      "Paper Cutting",
      "Embedded Figure",
      "Figure Completion",
      "Figure Series",
      "Cube & Dice",
    ],
  },
  English: {
    "Reading Comprehension": ["Fact", "Inference", "Title", "Vocabulary"],
    "Cloze Test": ["Grammar", "Vocabulary"],
    "Error Spotting": [
      "Noun",
      "Pronoun",
      "Verb",
      "Tense",
      "Article",
      "Preposition",
      "Conjunction",
      "Subject Verb Agreement",
      "Modifier",
      "Parallelism",
    ],
    "Sentence Improvement": ["Grammar", "Tense", "Voice", "Narration"],
    "Fill in the Blanks": ["Single", "Double", "Preposition", "Phrasal Verb"],
    Synonyms: ["Vocabulary", "Context"],
    Antonyms: ["Vocabulary", "Context"],
    "Idioms & Phrases": ["Meaning", "Usage"],
    "One Word Substitution": ["People", "Science", "Law", "General"],
    "Spelling Correction": ["Common Errors", "Homophones"],
    "Active Passive Voice": ["Present", "Past", "Future", "Modal"],
    "Direct Indirect Speech": [
      "Statements",
      "Questions",
      "Commands",
      "Exclamatory",
    ],
    "Para Jumbles": ["Sentence Arrangement", "Odd One Out"],
    "Sentence Rearrangement": ["Logical Sequence"],
    "Phrase Replacement": ["Grammar", "Vocabulary"],
  },
  "General Awareness": {
    History: [
      "Ancient India",
      "Medieval India",
      "Modern India",
      "Freedom Movement",
      "Art & Culture",
    ],
    Geography: ["Physical", "Indian", "World", "Environment"],
    "Indian Polity": [
      "Constitution",
      "Preamble",
      "Fundamental Rights",
      "Fundamental Duties",
      "DPSP",
      "President",
      "Prime Minister",
      "Parliament",
      "Judiciary",
      "Constitutional Bodies",
      "Emergency",
      "Amendments",
      "Schedules",
    ],
    Economics: [
      "Basic Economics",
      "Banking",
      "Budget",
      "Inflation",
      "Taxation",
      "GDP",
      "Monetary Policy",
      "Fiscal Policy",
      "Five Year Plans",
    ],
    "General Science": ["Physics", "Chemistry", "Biology", "Computer", "Space"],
    "Current Affairs": [
      "National",
      "International",
      "Sports",
      "Awards",
      "Appointments",
      "Books",
      "Science & Tech",
      "Economy",
      "Government Schemes",
    ],
    "Static GK": [
      "Important Days",
      "National Parks",
      "Rivers",
      "Dams",
      "Capitals",
      "Currencies",
      "Countries",
      "States",
      "Dances",
      "Festivals",
      "Temples",
      "UNESCO Sites",
      "Books",
      "Authors",
      "Awards",
      "Sports",
      "Stadiums",
    ],
  },
};
